# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
    build:
        working_directory: ~/Trials.com/react-frontend
        docker:
            - image: node:latest

        steps:
            - run:
                  name: Building Project
                  command: npm run build
            - run:
                  name: Testing Project
                  command: npm run test
            - run:
                  name: Deploying Project
                  command: npm run netlify:deploy
