# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
    build:
        docker:
            - image: node:latest

        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{checksum "~/project/Trials.com/react-frontend/package.json"}}
                      # Fallback to using latest cache
                      - v1-dependencies
            - run: npm install
            - save_cache:
                  paths:
                      - ~/project/Trials.com/react-frontend/node_modules
                  key: v1-dependencies-{{checksum "~/project/Trials.com/react-frontend/package.json"}}
            - run: |
                  echo "$(ls -a)"
                  cd Trials.com/react-frontend
                  echo "$(ls -a)"
                  CI= npm run build
                  npm run test
                  npm run netlify:deploy
