# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
    build-react-app:
        docker:
            - image: node:latest

        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{checksum "~/project/Trials.com/react-frontend/package.json"}}
                      # Fallback to using latest cache
                      - v1-dependencies
            - run: |
                  cd Trials.com/react-frontend
                  npm install
            - save_cache:
                  paths:
                      - ~/project/Trials.com/react-frontend/node_modules
                  key: v1-dependencies-{{checksum "~/project/Trials.com/react-frontend/package.json"}}
            - run: |
                  echo "$(ls -a)"
                  cd Trials.com/react-frontend
                  echo "$(ls -a)"
                  CI= npm run build
                  npm run test
                  npm run netlify:deploy

    build-node-server:
        docker:
            - image: node:latest

        steps:
            - add_ssh_keys:
                  fingerprints:
                      - "ed:97:54:a0:12:84:20:d7:39:60:ff:43:4b:86:fd:b8"
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{checksum "~/project/Trials.com/react-frontend/package.json"}}
                      # Fallback to using latest cache
                      - v1-dependencies
            - save_cache:
                  paths:
                      - ~/project/Trials.com/react-frontend/node_modules
                  key: v1-dependencies-{{checksum "~/project/Trials.com/react-frontend/package.json"}}
            - run: |
                  ssh-copy-id -i ~/.ssh/id_rsa  root@66.42.118.153
                  ssh -i ~/.ssh/id_rsa root@66.42.118.153

workflows:
    deploy:
        jobs:
            - build-react-app
            - build-node-server
