# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
    build:
        #app-dir: ~/project/Trials.com/react-frontend
        docker:
            - image: node:latest

        steps:
            - run:
                  name: Building Project
                  command: npm build
            - run:
                  name: Testing Project
                  command: npm test
            - run:
                  name: Deploying Project
                  command: npm netlify:deploy
