# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
    build:
        docker:
            - image: node:latest

        steps:
            - checkout
            - run: |
                  echo "$(ls -a)"
                  cd Trials.com/react-frontend
                  npm run build
                  npm run test
                  npm run netlify:deploy
