version: "3.8"
services:
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    prisma:
        image: prismagraphql/prisma:1.34.10
        restart: always
        ports:
            - "4466:4466"
        depends_on:
            - mysql-db
        environment:
            PRISMA_CONFIG: |
                port: 4466
                databases:
                    default:
                        connector: mysql
                        database: trialsnp
                        host: mysql-db
                        port: 3306
                        user: root
                        password: pass
                        connectionLimit: 2

    mysql-db:
        build:
            context: ./database
            dockerfile: Dockerfile
        command:
            [
                mysqld,
                --transaction-isolation=REPEATABLE-READ,
                --default-authentication-plugin=mysql_native_password,
                --character-set-server=utf8mb4,
                --collation-server=utf8mb4_unicode_ci,
                --innodb_monitor_enable=all,
                --max-connections=1001,
            ]
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - mysql:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 10s
            retries: 10

    node-server:
        build:
            context: ./node-server
            dockerfile: Dockerfile
        image: rjbradach/trialsnp-node
        ports:
            - "3002:3002"
        restart: always
        depends_on:
            - mysql-db

    react-frontend:
        build:
            context: ./react-frontend
            dockerfile: Dockerfile
        restart: always
        volumes:
            - /app/node_modules
            - ./react-frontend:/app
        environment:
            MYSQL_HOST: mysql-db
            NODE_ENV: production

        depends_on:
            - mysql-db
            - node-server
        ports:
            - "3000:3000"
        command: npm start
        env_file:
            - "./react-frontend/.env"

    nginx:
        depends_on:
            - node-server
            - react-frontend
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - "3050:80"

volumes:
    mysql: ~
